version: "3"
services:
  app:
    container_name: api
    restart: always
    build: .
    ports:
      - "2999:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"